In [1]:
print("officially started with my data science journey...! so happy and excited :)  ")

officially started with my data science journey...! so happy and excited :)  


# Started with Numpy:

In [3]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/da/3c/3ff05c2855eee52588f489a4e607e4a61699a0742aa03ccf641c77f9eb0a/numpy-1.26.2-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.2 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.2 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.2 kB 217.9 kB/s eta 0:00:01
     -------------------------------------- 61.2/61.2 kB 407.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   - -------------------------------------- 0.5/15.8 MB 15.0 MB/s eta 0:00:02
   ---- ----------------------------------- 1.6/15.8 MB 20.5 MB/s eta 0:00:01
   ------ --------------------------------- 2.7/15.8 MB 19.2 MB/s eta 0:00:01
   --------- ------------------------------ 3.8/15.8 MB 20.3 MB/s eta 0:00:01
   ------------ --------------------------- 5.0/15.8 MB 20.2 MB/s eta 0:00:01
   --------------- -----------


[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
import numpy as np

arr = np.array([1,2,3,4])

In [3]:
arr

array([1, 2, 3, 4])

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.empty(3)

array([0., 0., 0.])

In [8]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.arange(3,15,2)

array([ 3,  5,  7,  9, 11, 13])

In [12]:
np.linspace(5,10,num=10)

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

In [11]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [13]:
np.full((2,2),9)

array([[9, 9],
       [9, 9]])

In [15]:
np.full_like(9,4)

array(4)

In [16]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
a = np.array([[1,2] ,[3,4]])
np.tile(a,[1,5])

array([[1, 2, 1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4, 3, 4]])

In [23]:
a.dtype

dtype('int32')

In [24]:
a.shape


(2, 2)

In [25]:
a.ndim

2

In [26]:
a.size

4

In [28]:
a = np.array("2")

In [29]:
a.ndim

0

In [30]:
a.dtype

dtype('<U1')

In [36]:
a1 = np.array([1,5])
a2 = np.array([8,9])
res = np.hstack((a1,a2))
print(res)

[1 5 8 9]


In [40]:
res = np.vstack((a1,a2))
print(res)

[[1 5]
 [8 9]]


In [41]:
np.random.rand(2,3)

array([[0.0159525 , 0.15826689, 0.52834662],
       [0.66264166, 0.00234544, 0.51936086]])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.eye(3,k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [45]:
np.diag(np.array([1,2,3]))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [46]:
np.eye(5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.concatenate((a1,a2))

array([1, 5, 8, 9])

In [6]:
a1 = np.array([[1,5,3,4,5,8]])
a1.reshape(3,2)

array([[1, 5],
       [3, 4],
       [5, 8]])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(5,dtype=float)

array([0., 1., 2., 3., 4.])

In [10]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [14]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
np.diag([10,20,30],1)

array([[ 0, 10,  0,  0],
       [ 0,  0, 20,  0],
       [ 0,  0,  0, 30],
       [ 0,  0,  0,  0]])

In [21]:
np.vander([1,2,3,4,5],2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1],
       [5, 1]])

In [27]:
a = np.array([1,2,3,4,5])
b = a[:2]
b+=1
print("A", a,"b",b)

A [2 3 3 4 5] b [2 3]
